//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristAgency.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TouristAgencyEntities : DbContext
    {
        public TouristAgencyEntities()
            : base("name=TouristAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<PlaceResidence> PlaceResidence { get; set; }
        public virtual DbSet<TourAgent> TourAgent { get; set; }
        public virtual DbSet<TravelPackage> TravelPackage { get; set; }
        public virtual DbSet<TravelPackageClient> TravelPackageClient { get; set; }
        public virtual DbSet<WayMoving> WayMoving { get; set; }
    }
}
