//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristAgency.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelPackage()
        {
            this.TravelPackageClient = new HashSet<TravelPackageClient>();
        }
    
        public int ID { get; set; }
        public decimal Price { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public System.TimeSpan ReturnTime { get; set; }
        public string Route { get; set; }
        public int WayMovingID { get; set; }
        public int PlaceResidenceID { get; set; }
        public bool Excursion { get; set; }
        public bool Hot { get; set; }
        public Nullable<int> TourAgentID { get; set; }
    
        public virtual PlaceResidence PlaceResidence { get; set; }
        public virtual TourAgent TourAgent { get; set; }
        public virtual WayMoving WayMoving { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelPackageClient> TravelPackageClient { get; set; }
    }
}
